### PR TITLE
added ModelCheckpoint import in complete code

### PR DESCRIPTION
**Pull request by Ishan-Kumar2**
I was using the complete code of the Getting Started tutorial and it was giving the error that ``from ignite.handlers import ModelCheckpoint`` was missing, so I have added that [here](https://github.com/pytorch-ignite/examples/pull/74/commits/86958c6d97a863d658e55ca553b72e4047dc9393#diff-7c16c2ca0967bb26b49f9df5ab907b6a0ca1741eb16d72f4b4bedc3e116ed21cR625)

### CODE REVIEW

**Comment by sdesrozis** [comment]
@Ishan-Kumar2 Thanks for your exploration. However, the import was in the original notebook, so I suppose I didn't catch the issue...

Could you do a minimal modification in the notebook ? Actually it's impossible to track what you did. Thanks in advance !

**Comment by Ishan-Kumar2** [comment]
Hi @sdesrozis, the complete code added in a markdown cell doesn't have this import. Its the last cell of the notebook 
image
I am not sure what causes the diff to become so large I just changed this one line. Please let me know if there is a way to get rid of these extra changes.

**Comment by Priyansi** [comment]
Hey @Ishan-Kumar2 thanks for catching this. Actually, for markdown changes like these, I prefer to edit the raw Jupyter notebook so it becomes easier for git to track.

cc @sdesrozis

**Comment by sdesrozis** [comment]
@Priyansi @Ishan-Kumar2 agreed about the raw editing if possible !!

**Comment by Ishan-Kumar2** [comment]
@Priyansi @sdesrozis sorry for the delay, I have made the change in the raw file now. Please have a look

**Review by sdesrozis — APPROVED** [review]
Thanks @Ishan-Kumar2 LGTM

**Pull request merged**
