### PR TITLE
feat: add notebook generating script

### PR DESCRIPTION
**Pull request by ydcjeff**
This could help essential frontmatters to be in every notebooks without having to remember all the required frontmatters.

External contributors can also have right frontmatters easily.

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Thanks @ydcjeff !

**Comment by vfdev-5** [comment]
What would be suggested workflow: when to use this script ?

**Comment by ydcjeff** [comment]
> What would be suggested workflow: when to use this script ?

This script can be used anytime to have same essential frontmatters instead of typing manually.

**Comment by vfdev-5** [comment]
Yes, I understand that, but should we put a note somewhere about that ?

**Pull request merged**
