### PR TITLE
added basic guide

### PR DESCRIPTION
**Pull request by Priyansi**

### CODE REVIEW

**Comment by Ishan-Kumar2** [comment]
@Priyansi @vfdev-5 what do you think about having a black code formatter for examples also? There are multiple options of running black with jupyter, one which I tested is [this](https://github.com/irahorecka/jupyterblack), it works well.

**Comment by Priyansi** [comment]
Thanks for the great suggestion @Ishan-Kumar2 ! What do you think about it @vfdev-5 ?
cc @trsvchn

**Comment by vfdev-5** [comment]
@Ishan-Kumar2 never used this jupyterblack before, maybe it could be interesting to use it. I'm a bit curious about adoption of it by others. The repository does not seem to be active : no issues by users...
I let @Priyansi and @trsvchn to say their word, I'm ok to go without it.

**Comment by vfdev-5** [comment]
psf/black provides an option for jupyter : https://github.com/psf/black#installation

**Pull request merged**
