### PR TITLE
added collective communication tutorial

### LINKED ISSUE #16: `idist` tutorial
A new advanced standalone tutorial on `idist` that doesn't rely on comparison as in the blog post [Distributed Made Easy with Ignite](https://labs.quansight.org/blog/2021/06/distributed-made-easy-with-ignite/) but focuses more on `idist` methods like `all_reduce` and `all_gather` and `broadcast`.

### PR DESCRIPTION
**Pull request by Priyansi**
Fixes #16

### CODE REVIEW

**Comment by Priyansi** [comment]
Hey @vfdev-5 , I replaced, `Parallel` with `spawn`. Also, I noticed that the `args` parameter is required for [`spawn`](https://pytorch.org/ignite/v0.4.7/distributed.html#ignite.distributed.utils.spawn) and I wondered why as I didn't have the need to pass any args for these examples.

**Comment by vfdev-5** [comment]
> Also, I noticed that the args parameter is required for spawn and I wondered why as I didn't have the need to pass any args for these examples.

basically, args can be global configuration that user would like to pass into spawn function. In your case, functions are very trivial and do not represent real use-cases...

**Review by vfdev-5 — APPROVED** [review]
Thanks @Priyansi , lgtm

**Comment by Priyansi** [comment]
> basically, args can be global configuration that user would like to pass into spawn function. In your case, functions are very trivial and do not represent real use-cases...

No, I was just wondering if it's necessary to make it required. Anyway, I got it!

**Pull request merged**
