### PR TITLE
Added how-to guide: Loggers

### LINKED ISSUE #44: Logging in Ignite
It would be nice to have a how-to guide combine all the built-in loggers that Ignite provides: ClearML, Tensorboard, MLflow, etc. See more here: https://pytorch.org/ignite/contrib/handlers.html#loggers.
The code on how to use these is already provided in https://github.com/pytorch/ignite/tree/master/examples/contrib/mnist.
When creating this new how-to guide, please:
1. Create a Jupyter Notebook, see README.md.
2. Follow the code under the basic setup of how-to guides. See this guide for [reference](https://pytorch-ignite.ai/how-to-guides/04-fastai-lr-finder/#basic-setup).
2. Add explanation while creating the loggers and how to use them.
3. Run the notebook, so that the output is clearly visible, before submitting the PR.

Everyone is welcome to contribute! :rocket: Please feel free to ask any further questions below.

### PR DESCRIPTION
**Pull request by anirudhb11**
Resolves #44, 
A how-to guide for loggers in Ignite. Demonstrates the usage with one logger (`ClearML`) and how the usage can be extended to other loggers

### CODE REVIEW

**Comment by vfdev-5** [comment]
@anirudhb11 could you please update the PR and we could land it. Thanks a lot 1

**Comment by anirudhb11** [comment]
> @anirudhb11 could you please update the PR and we could land it. Thanks a lot !

@vfdev-5 thanks for reminder, apologies for the delayed response, have added a brief explanation regarding the usage as requested by @Priyansi

**Comment by vfdev-5** [comment]
@anirudhb11 Thanks for the update! I let @Priyansi review this PR and merge if everything is ok.

By the way, we are using `<!--more-->` tag (see https://github.com/pytorch-ignite/examples/blob/main/generate.py#L34-L56) to show short description of the guide in the list. For example https://raw.githubusercontent.com/pytorch-ignite/examples/main/how-to-guides/06-data-iterator.ipynb

Could you please add that as well.

**Comment by Priyansi** [comment]
Thanks so much @anirudhb11 for adding the explanation! We should be good to merge once @vfdev-5 's comment is resolved.

**Comment by anirudhb11** [comment]
Have added a `<!--more-->` tag to state the dataset and model being used in the task

**Review by vfdev-5 — APPROVED** [review]
Thanks a lot the PR @anirudhb11 
LGTM!

**Pull request merged**
